import os

NAME_DATABASE_ARTEMIS = os.environ.get('NAME_DATABASE_ARTEMIS')
USER_DATABASE_ARTEMIS = os.environ.get('USER_DATABASE_ARTEMIS')
PASSWORD_DATABASE_ARTEMIS = os.environ.get('PASSWORD_DATABASE_ARTEMIS')
HOST_DATABASE_ARTEMIS = os.environ.get('HOST_DATABASE_ARTEMIS')
PORT_DATABASE_ARTEMIS = os.environ.get('PORT_DATABASE_ARTEMIS')
